"""Alembic environment.

The schema is authored as raw SQL inside the migration files rather than being
autogenerated from ORM models. Reasons, in order:

  * Partitioned tables, partial/expression indexes, generated columns, rules and
    triggers are all things Alembic autogenerate does not round-trip correctly.
  * The migrations are the canonical schema and must be reviewable by a human
    reading SQL, not a human reading `sa.Column(...)` builders.
  * ORM models are declared per module (see app/modules/*/models.py) and are
    deliberately NOT joined into a single MetaData — that would create the exact
    cross-module coupling the module boundaries exist to prevent.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Read straight from the environment and hand the URL to create_engine, rather
# than round-tripping it through `config.set_main_option`. alembic.ini is parsed
# by configparser, which treats `%` as interpolation — so a URL-encoded socket
# path (`host=%2Ftmp`) or a password containing `%` would fail at deploy time
# with an error that points nowhere near the cause.
DATABASE_URL = os.environ.get("DATABASE_URL") or config.get_main_option("sqlalchemy.url")

# Raw-SQL migrations: there is no model metadata to diff against.
target_metadata = None


def run_migrations_offline() -> None:
    context.configure(
        url=DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(DATABASE_URL, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
