"""Media, end to end: upload → ingest → grant → stream.

Real ffmpeg, real bytes, real HTTP. The audio tests skip cleanly where ffmpeg is
absent, the same way the integration suite skips without a database — but they
are not mocked, because the two things worth proving here cannot be proven with a
fake:

  * that loudness normalisation actually lands on target, which is what stops a
    student losing exam time to the volume slider between sections;
  * that a grant issued for one student does not open the file for another, which
    is the whole anti-scrape story.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import subprocess
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import text

from app.api.deps import issue_access_token
from app.platform import audio as ffmpeg
from app.platform import grants
from app.platform.errors import Forbidden
from app.platform.storage import FileStorage, set_storage

needs_ffmpeg = pytest.mark.skipif(not ffmpeg.available(),
                                  reason="ffmpeg is not installed")


@pytest.fixture
def store(tmp_path):
    """A file-backed store rooted in the test's own directory.

    Installed process-wide because the API and the worker both resolve
    `storage()` themselves — which is the point of the singleton, and the reason
    this fixture must put it back afterwards.
    """
    backend = FileStorage(root=tmp_path / "media", bucket="test-media")
    set_storage(backend)
    yield backend
    set_storage(None)


@pytest.fixture
def client(engine, db, store):
    from app.api import deps
    from app.api.main import create_app

    app = create_app()
    app.dependency_overrides[deps.db] = lambda: db
    with TestClient(app, raise_server_exceptions=False) as c:
        yield c


@pytest.fixture
def author_auth(seed):
    return {"Authorization": f"Bearer {issue_access_token(str(seed['author'].xid))}"}


@pytest.fixture
def wav(tmp_path) -> Path:
    """Ten seconds, quiet overall, and DYNAMIC — alternating loud and soft.

    Both properties are deliberate. Quiet, so a file already at target would not
    pass the normalisation test whether or not it ran. Dynamic, because that is
    the only way to tell one-pass loudnorm from two-pass: on a steady tone both
    land on target, and the difference only appears when there is a loudness
    range to preserve or compress. It stands in for two speakers at different
    levels, which is what an IELTS listening section actually is.

    The guard lives on the FIXTURE rather than only on the classes that encode
    audio, because it is generated BY ffmpeg. Two tests in `TestResumableUpload`
    take this fixture without being marked `@needs_ffmpeg` and errored on a
    machine without it, against a README that promises they skip cleanly. On the
    fixture the mark cannot be forgotten by the next test that needs a wav.
    """
    if not ffmpeg.available():
        pytest.skip("ffmpeg is not installed")
    path = tmp_path / "master.wav"
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
         "-i", "sine=frequency=220:duration=10:sample_rate=48000",
         "-af", "volume='if(lt(mod(t,4),2),0.02,0.6)':eval=frame",
         "-ac", "2", "-c:a", "pcm_s16le", str(path)],
        check=True)
    return path


ATTESTATION = {"claim": "original", "statement_version": "1"}


def create_track(client, auth, *, filename="master.wav", bytes_=1_152_078,
                 content_type="audio/wav", attestation=None, title="Section 1"):
    return client.post("/api/v1/audio-tracks", headers=auth, json={
        "title": title, "accent": "en-GB", "filename": filename,
        "bytes": bytes_, "content_type": content_type,
        "attestation": attestation if attestation is not None else ATTESTATION})


class TestUploadValidation:
    def test_an_upload_without_an_attestation_is_refused(self, client, author_auth):
        """Refused, not defaulted.

        A missing attestation that quietly becomes "original" manufactures a
        claim the uploader never made, which is the opposite of evidence.
        """
        r = create_track(client, author_auth, attestation={})
        assert r.status_code == 422, r.text
        assert any(f["code"] == "ATTESTATION_REQUIRED" for f in r.json()["findings"])

    def test_a_licensed_upload_must_say_what_the_licence_is(self, client, author_auth):
        r = create_track(client, author_auth, attestation={"claim": "licensed"})
        assert r.status_code == 422
        assert any(f["code"] == "LICENCE_NOTE_REQUIRED" for f in r.json()["findings"])

    def test_an_unsupported_format_is_refused_before_the_bytes_are_sent(
            self, client, author_auth):
        """The whole reason validation happens at open, not at complete: a
        teacher on a metered connection must not send 40 MB to be told no."""
        r = create_track(client, author_auth, content_type="application/zip")
        assert r.status_code == 422
        assert any(f["code"] == "MEDIA_TYPE_UNSUPPORTED" for f in r.json()["findings"])

    def test_an_oversized_file_is_refused(self, client, author_auth):
        r = create_track(client, author_auth, bytes_=900 * 1024 * 1024)
        assert r.status_code == 422
        assert any(f["code"] == "MEDIA_TOO_LARGE" for f in r.json()["findings"])

    def test_every_problem_is_returned_at_once(self, client, author_auth):
        r = create_track(client, author_auth, content_type="application/zip",
                         bytes_=0, attestation={})
        codes = {f["code"] for f in r.json()["findings"]}
        assert {"MEDIA_TYPE_UNSUPPORTED", "MEDIA_EMPTY",
                "ATTESTATION_REQUIRED"} <= codes

    def test_the_attestation_records_the_statement_hash(self, client, author_auth, db):
        """"They ticked a box" is not a defence. "They ticked THIS box, whose
        text hashed to X" is."""
        import hashlib

        from app.modules.content.media import ATTESTATION_STATEMENTS

        assert create_track(client, author_auth).status_code == 201
        # Scoped to the two media subjects. The seed's passage carries an
        # attestation of its own now — `POST /passages` writes one — and an
        # unfiltered SELECT here was asserting that no other subject type in the
        # system had ever been attested, which was never what this test meant.
        rows = db.execute(text("""
            SELECT subject_type, claim, statement_key, statement_version,
                   statement_hash, user_agent_hash
            FROM content_attestations
            WHERE subject_type IN ('audio_track', 'media_asset')
            ORDER BY subject_type
        """)).mappings().all()
        # One against the media asset, one against the track a takedown names.
        assert {r["subject_type"] for r in rows} == {"audio_track", "media_asset"}
        expected = hashlib.sha256(
            ATTESTATION_STATEMENTS["upload"]["text"].encode()).hexdigest()
        assert all(r["statement_hash"] == expected for r in rows)
        assert all(r["claim"] == "original" for r in rows)


class TestResumableUpload:
    def test_opening_an_upload_returns_presigned_parts(self, client, author_auth):
        body = create_track(client, author_auth, bytes_=12 * 1024 * 1024).json()
        upload = body["upload"]
        assert upload["part_size"] == 5 * 1024 * 1024
        # 12 MB over 5 MB parts is three.
        assert [p["n"] for p in upload["presigned_urls"]] == [1, 2, 3]
        assert body["audio_track"]["status"] == "processing"

    def test_a_dropped_upload_resumes_with_only_the_missing_parts(
            self, client, author_auth, store):
        """The point of the whole mechanism: a 40 MB file on a connection that
        drops every ninety seconds."""
        upload = create_track(client, author_auth,
                              bytes_=12 * 1024 * 1024).json()["upload"]
        first = upload["presigned_urls"][0]
        assert _put_part(client, first, b"x" * 1024).status_code == 200

        # The client reconnects and asks what is still owed.
        resumed = client.get(f"/api/v1/uploads/{upload['xid']}",
                             headers=author_auth).json()
        assert resumed["parts_received"] == []          # not yet reported complete
        assert [p["n"] for p in resumed["presigned_urls"]] == [1, 2, 3]

    def test_completing_assembles_the_object_and_queues_ingest(
            self, client, author_auth, db, store, wav):
        upload = create_track(client, author_auth,
                              bytes_=wav.stat().st_size).json()["upload"]
        _upload_file(client, upload, wav)

        done = client.post(f"/api/v1/uploads/{upload['xid']}", headers=author_auth,
                           json={"parts": _parts_for(wav)})
        assert done.status_code == 202, done.text
        assert done.json()["status"] == "processing"

        # The ingest event is written in the SAME transaction as the status
        # change, so an upload that completed without a transcode job is not
        # representable.
        assert db.scalar(text("""
            SELECT count(*) FROM outbox WHERE event_type = 'media.uploaded'
        """)) == 1

    def test_completing_twice_is_idempotent(self, client, author_auth, store, wav):
        upload = create_track(client, author_auth,
                              bytes_=wav.stat().st_size).json()["upload"]
        _upload_file(client, upload, wav)
        parts = _parts_for(wav)
        first = client.post(f"/api/v1/uploads/{upload['xid']}", headers=author_auth,
                            json={"parts": parts})
        second = client.post(f"/api/v1/uploads/{upload['xid']}", headers=author_auth,
                             json={"parts": parts})
        assert second.status_code == 202
        assert first.json()["xid"] == second.json()["xid"]

    def test_another_user_cannot_read_or_complete_my_upload(self, client, seed,
                                                            author_auth):
        upload = create_track(client, author_auth).json()["upload"]
        student = {"Authorization":
                   f"Bearer {issue_access_token(str(seed['student'].xid))}"}
        assert client.get(f"/api/v1/uploads/{upload['xid']}",
                          headers=student).status_code == 404
        assert client.post(f"/api/v1/uploads/{upload['xid']}", headers=student,
                           json={"parts": []}).status_code == 404

    def test_aborting_releases_the_upload(self, client, author_auth, db):
        upload = create_track(client, author_auth).json()["upload"]
        assert client.delete(f"/api/v1/uploads/{upload['xid']}",
                             headers=author_auth).status_code == 204
        assert db.scalar(text("SELECT status FROM media_uploads WHERE xid = CAST(:x AS uuid)")
                         .bindparams(x=upload["xid"])) == "aborted"
        assert db.scalar(text("""
            SELECT status FROM media_assets WHERE xid = CAST(:x AS uuid)
        """).bindparams(x=upload["media_xid"])) == "removed"


@needs_ffmpeg
class TestIngest:
    def test_a_quiet_upload_is_normalised_to_target(self, client, author_auth, db,
                                                    store, wav, tmp_path):
        """Lands on target, and PRESERVES the loudness range.

        The second assertion is the one that justifies two passes. Single-pass
        `loudnorm` is a dynamic compressor: it also reaches roughly the target,
        but it squashes the range on the way — measured at +0.6 LRA on this
        fixture versus +0.1 for two-pass. Compressing an exam recording changes
        the relative levels of its speakers, which is a content change nobody
        asked for and which no author would notice until a student complained
        they could not hear one of them.
        """
        source_lra = ffmpeg.measure(wav).lra
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        row = db.execute(text("""
            SELECT m.loudness_lufs AS master_lufs, m.duration_ms, m.status,
                   d.id AS delivery_id, d.content_type, d.bytes AS delivery_bytes,
                   d.channels, d.sample_rate
            FROM media_assets m
            LEFT JOIN media_assets d ON d.derived_from_id = m.id
            WHERE m.id = :id
        """).bindparams(id=asset_id)).mappings().one()

        assert row["status"] == "ready"
        # Well below target, so the normalisation had real work to do.
        assert float(row["master_lufs"]) < ffmpeg.TARGET_LUFS - 8
        assert row["duration_ms"] == pytest.approx(10_000, abs=100)
        assert row["content_type"] == ffmpeg.DELIVERY_CONTENT_TYPE
        assert row["channels"] == 1 and row["sample_rate"] == 44_100

        delivered = tmp_path / "out.m4a"
        store.download(db.scalar(text("SELECT storage_key FROM media_assets WHERE id = :i")
                                 .bindparams(i=row["delivery_id"])), delivered)
        measured = ffmpeg.measure(delivered)
        assert measured.integrated_lufs == pytest.approx(ffmpeg.TARGET_LUFS, abs=0.2)
        # The discriminating assertion. Two-pass applies a linear gain, so the
        # range survives; one-pass would widen it by roughly half a unit here.
        assert measured.lra == pytest.approx(source_lra, abs=0.25)

    def test_the_delivery_file_is_far_smaller_than_the_master(
            self, client, author_auth, db, store, wav, tmp_path):
        """Every byte is origin egress on the proxy path, so this ratio is the
        monthly bill."""
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        row = db.execute(text("""
            SELECT m.bytes AS master, d.bytes AS delivery
            FROM media_assets m JOIN media_assets d ON d.derived_from_id = m.id
            WHERE m.id = :id
        """).bindparams(id=asset_id)).mappings().one()
        assert row["delivery"] < row["master"] / 5

    def test_the_track_becomes_ready_with_its_measurements(
            self, client, author_auth, db, store, wav, tmp_path):
        _ingest(client, author_auth, db, store, wav, tmp_path)
        track_xid = db.scalar(text("SELECT xid FROM audio_tracks LIMIT 1"))
        body = client.get(f"/api/v1/audio-tracks/{track_xid}",
                          headers=author_auth).json()
        assert body["status"] == "ready"
        assert body["duration_ms"] == pytest.approx(10_000, abs=100)
        assert body["loudness_lufs"] == ffmpeg.TARGET_LUFS

    def test_ingesting_twice_does_not_re_encode(self, client, author_auth, db,
                                                store, wav, tmp_path):
        """The relay is at-least-once, and re-encoding a thirty-minute file costs
        a minute of CPU each time."""
        from app.modules.content import media as media_service

        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        before = db.scalar(text(
            "SELECT count(*) FROM media_assets WHERE derived_from_id = :i"
        ).bindparams(i=asset_id))
        media_service.ingest_audio(db, store, asset_id, now=dt.datetime.now(dt.UTC),
                                   scratch=tmp_path)
        assert db.scalar(text(
            "SELECT count(*) FROM media_assets WHERE derived_from_id = :i"
        ).bindparams(i=asset_id)) == before == 1

    def test_a_silent_upload_is_rejected_with_a_reason_the_author_can_act_on(
            self, client, author_auth, db, store, tmp_path):
        """"Your file was silent, check the export" is actionable. "Failed" is a
        support ticket."""

        silent = tmp_path / "silent.wav"
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
             "-i", "anullsrc=r=44100:cl=mono", "-t", "4",
             "-c:a", "pcm_s16le", str(silent)], check=True)

        asset_id = _ingest(client, author_auth, db, store, silent, tmp_path,
                           expect_ready=False)
        row = db.execute(text("""
            SELECT status, processing_error FROM media_assets WHERE id = :i
        """).bindparams(i=asset_id)).mappings().one()
        assert row["status"] == "failed"
        assert "silent" in row["processing_error"].lower()

        track_xid = db.scalar(text("SELECT xid FROM audio_tracks LIMIT 1"))
        body = client.get(f"/api/v1/audio-tracks/{track_xid}",
                          headers=author_auth).json()
        assert body["status"] == "failed"
        assert "silent" in body["processing_error"].lower()

    def test_a_video_file_is_refused_for_having_no_audio_stream(self, tmp_path):
        """The mistake a teacher actually makes: uploading the screen recording
        rather than the exported audio.

        ffprobe parses it perfectly — it is a valid media file — so the "not
        audio" check one test down does not catch it. What is missing is an audio
        STREAM, and the message has to say that rather than "invalid file", or the
        teacher re-exports the same video.
        """
        silent_video = tmp_path / "recording.mp4"
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
             "-i", "color=c=black:s=320x240:d=2", str(silent_video)], check=True)

        with pytest.raises(ffmpeg.AudioError, match="no audio stream"):
            ffmpeg.probe(silent_video)

    def test_a_file_that_is_not_audio_fails_cleanly(self, client, author_auth, db,
                                                    store, tmp_path):
        from app.modules.content import media as media_service

        junk = tmp_path / "not-audio.wav"
        junk.write_bytes(b"RIFF" + b"\x00" * 2048)
        asset_id = _ingest(client, author_auth, db, store, junk, tmp_path,
                           expect_ready=False)
        assert db.scalar(text("SELECT status FROM media_assets WHERE id = :i")
                         .bindparams(i=asset_id)) == "failed"
        _ = media_service

    def test_uploader_metadata_is_stripped_from_the_delivery_file(
            self, client, author_auth, db, store, tmp_path):
        """An uploaded WAV can carry the teacher's name, their software licence
        and sometimes a path from their laptop. None of that reaches a student."""
        tagged = tmp_path / "tagged.wav"
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
             "-i", "sine=frequency=300:duration=3", "-metadata",
             "artist=Dilnoza Karimova", "-metadata", "comment=C:/Users/dilnoza/ielts",
             "-c:a", "pcm_s16le", str(tagged)], check=True)

        asset_id = _ingest(client, author_auth, db, store, tagged, tmp_path)
        key = db.scalar(text("""
            SELECT storage_key FROM media_assets WHERE derived_from_id = :i
        """).bindparams(i=asset_id))
        out = tmp_path / "check.m4a"
        store.download(key, out)
        assert b"Dilnoza" not in out.read_bytes()
        assert b"dilnoza" not in out.read_bytes()


@needs_ffmpeg
class TestDelivery:
    def test_a_student_streams_the_delivery_file_with_a_grant(
            self, client, author_auth, db, store, wav, tmp_path, seed):
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        media_xid, student_xid = _delivery_and_student(db, asset_id, seed)

        grant = grants.issue(user_xid=student_xid, media_xid=media_xid)
        r = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}")
        assert r.status_code == 200, r.text
        assert r.headers["content-type"].startswith("audio/mp4")
        assert r.headers["accept-ranges"] == "bytes"
        # A shared device in a computer lab must not keep an exam section in its
        # disk cache after the student logs out.
        assert r.headers["cache-control"] == "no-store"
        assert len(r.content) > 1000

    def test_an_asset_in_another_bucket_is_served_from_that_bucket(
            self, client, db, store, seed):
        """`media_assets.bucket` was written on every upload and read by nothing:
        delivery resolved the CONFIGURED bucket and looked the key up there.

        An object anywhere else therefore streamed ZERO BYTES behind a correct
        `Content-Length` — which the client sees as a truncated 200 and the
        operator as a uvicorn protocol error, rather than as anything nameable.

        The column is what keeps "we may be required to store this in-country" a
        config change: a migration leaves old rows on the old bucket and new rows
        on the new one, and only a reader that honours the column serves both.
        """
        from app.platform.storage import FileStorage

        body = b"in-country" * 200
        # Beside the installed store, not under the configured media root: this
        # fixture roots storage in the test's own directory.
        other = FileStorage(root=store.root.parent, bucket="ielts-media-tashkent")
        other.put("moved/section.m4a", body, content_type="audio/mp4")

        media_xid = str(db.scalar(text("""
            INSERT INTO media_assets (owner_user_id, kind, bucket, storage_key,
                                      content_type, bytes, checksum_sha256, status)
            VALUES (:u, 'audio', 'ielts-media-tashkent', 'moved/section.m4a',
                    'audio/mp4', :n, 'x', 'ready')
            RETURNING xid
        """).bindparams(u=seed["author"].id, n=len(body))))
        db.flush()

        grant = grants.issue(user_xid=str(seed["student"].xid), media_xid=media_xid)
        r = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}")
        assert r.status_code == 200, r.text
        assert r.content == body

    def test_a_missing_object_is_an_error_not_a_truncated_200(
            self, client, db, store, seed):
        """`StreamingResponse` sends the headers first and only then pulls the
        generator, so a storage read that fails cannot become a status code: the
        client got a 200 whose body stopped early. Statting first is what turns
        the failure into something a person can read."""
        media_xid = str(db.scalar(text("""
            INSERT INTO media_assets (owner_user_id, kind, bucket, storage_key,
                                      content_type, bytes, checksum_sha256, status)
            VALUES (:u, 'audio', :b, 'gone/never-written.m4a', 'audio/mp4',
                    4096, 'x', 'ready')
            RETURNING xid
        """).bindparams(u=seed["author"].id, b=store.bucket)))
        db.flush()

        grant = grants.issue(user_xid=str(seed["student"].xid), media_xid=media_xid)
        r = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}")
        assert r.status_code == 404, r.text
        assert r.json()["code"] == "media_object_missing"

    def test_a_range_request_returns_206_and_the_right_slice(
            self, client, author_auth, db, store, wav, tmp_path, seed):
        """Without range support an <audio> element cannot seek, and on iOS
        Safari it will not play at all."""
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        media_xid, student_xid = _delivery_and_student(db, asset_id, seed)
        grant = grants.issue(user_xid=student_xid, media_xid=media_xid)

        whole = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}").content
        partial = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}",
                             headers={"Range": "bytes=100-199"})
        assert partial.status_code == 206
        assert partial.headers["content-range"] == f"bytes 100-199/{len(whole)}"
        assert partial.content == whole[100:200]

    def test_an_open_ended_range_runs_to_the_end(self, client, author_auth, db,
                                                 store, wav, tmp_path, seed):
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        media_xid, student_xid = _delivery_and_student(db, asset_id, seed)
        grant = grants.issue(user_xid=student_xid, media_xid=media_xid)
        whole = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}").content
        tail = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}",
                          headers={"Range": "bytes=1000-"})
        assert tail.status_code == 206
        assert tail.content == whole[1000:]

    def test_the_master_is_never_served_when_a_delivery_exists(
            self, client, author_auth, db, store, wav, tmp_path, seed):
        """An author's xid names the MASTER. A student asking for it must not
        receive a 400 MB wav."""
        asset_id = _ingest(client, author_auth, db, store, wav, tmp_path)
        master_xid = str(db.scalar(text("SELECT xid FROM media_assets WHERE id = :i")
                                   .bindparams(i=asset_id)))
        student_xid = str(seed["student"].xid)
        grant = grants.issue(user_xid=student_xid, media_xid=master_xid)
        r = client.get(f"/api/v1/media/{master_xid}/content?grant={grant}")
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("audio/mp4")
        assert len(r.content) < wav.stat().st_size / 5


class TestDeliveryRanges:
    """The per-user path answers the same 200/206/416 as the presigned one.

    It had its own `Range` parser, which clamped a request beginning past the
    end into a one-byte 206 and answered a malformed header with a 206 and a
    `Content-Range`, while `/internal/storage` sent 416 and the whole object
    respectively. Which answer a player got for the same header was decided by
    `media_delivery`, a config knob. These are the cases the storage route
    already pins (`test_object_storage.py::TestRanges`), held against this route.

    No ffmpeg: the row is written straight at a stored object, the same way the
    bucket test above does it, because a range is about bytes and not audio.
    """

    @pytest.fixture
    def section(self, db, store, seed) -> tuple[str, bytes, str]:
        """A 300 KB object, big enough that a range is a different answer."""
        body = bytes(range(256)) * 1200
        store.put("ranges/section.m4a", body, content_type="audio/mp4")
        media_xid = str(db.scalar(text("""
            INSERT INTO media_assets (owner_user_id, kind, bucket, storage_key,
                                      content_type, bytes, checksum_sha256, status)
            VALUES (:u, 'audio', :b, 'ranges/section.m4a', 'audio/mp4', :n, 'x',
                    'ready')
            RETURNING xid
        """).bindparams(u=seed["author"].id, b=store.bucket, n=len(body))))
        db.flush()
        grant = grants.issue(user_xid=str(seed["student"].xid), media_xid=media_xid)
        return f"/api/v1/media/{media_xid}/content?grant={grant}", body, media_xid

    def test_the_whole_object_when_no_range_is_asked_for(self, client, section):
        url, stored, _ = section
        response = client.get(url)
        assert response.status_code == 200
        assert response.content == stored
        assert response.headers["Content-Length"] == str(len(stored))
        assert "Content-Range" not in response.headers

    def test_a_suffix_range(self, client, section):
        """`bytes=-500` — the last 500 bytes. Players use it to read a trailing
        atom before deciding how to stream the rest."""
        url, stored, _ = section
        response = client.get(url, headers={"Range": "bytes=-500"})
        assert response.status_code == 206
        assert response.content == stored[-500:]
        assert response.headers["Content-Range"] == (
            f"bytes {len(stored) - 500}-{len(stored) - 1}/{len(stored)}")

    def test_a_range_past_the_end_is_a_416(self, client, section):
        """Not a one-byte 206 of the last byte, which is what the clamp made of
        it — a player that reads that as "the file is one byte" stops."""
        url, stored, _ = section
        response = client.get(url, headers={"Range": f"bytes={len(stored) + 10}-"})
        assert response.status_code == 416
        assert response.headers["Content-Range"] == f"bytes */{len(stored)}"
        assert response.headers["Cache-Control"] == "no-store"

    def test_a_range_that_overruns_the_end_is_clamped(self, client, section):
        """A player that asks for more than there is gets what there is, not a
        416 — this is the ordinary last-chunk request."""
        url, stored, _ = section
        response = client.get(url, headers={"Range": f"bytes=0-{len(stored) + 500}"})
        assert response.status_code == 206
        assert response.content == stored

    @pytest.mark.parametrize("header", ["bytes=abc", "items=0-10", "bytes=-", "",
                                        "bytes=500-100"])
    def test_a_malformed_range_sends_the_whole_thing(self, client, section, header):
        """Ignored rather than refused. A malformed Range means "send the whole
        thing"; refusing would break a player over a header it did not have to
        send. And a plain 200 — the old parser sent a 206 with a `Content-Range`
        for a header it had not understood."""
        url, stored, _ = section
        response = client.get(url, headers={"Range": header} if header else {})
        assert response.status_code == 200
        assert response.content == stored
        assert "Content-Range" not in response.headers


class TestGrants:
    """The anti-scrape mechanism. Pure, so it needs no ffmpeg."""

    def test_a_valid_grant_verifies(self):
        token = grants.issue(user_xid="u-1", media_xid="m-1")
        claim = grants.verify(token, user_xid="u-1", media_xid="m-1")
        assert claim.user_xid == "u-1" and claim.purpose == "exam"

    def test_a_grant_for_another_user_is_refused(self):
        """Without this binding, one student's grant leaked from devtools is a
        download link for the whole class."""
        token = grants.issue(user_xid="u-1", media_xid="m-1")
        with pytest.raises(Exception) as exc:
            grants.verify(token, user_xid="u-2", media_xid="m-1")
        assert exc.value.code == "grant_wrong_user"

    def test_a_grant_for_another_object_is_refused(self):
        token = grants.issue(user_xid="u-1", media_xid="m-1")
        with pytest.raises(Exception) as exc:
            grants.verify(token, user_xid="u-1", media_xid="m-2")
        assert exc.value.code == "grant_wrong_media"

    def test_an_expired_grant_is_refused(self):
        past = dt.datetime.now(dt.UTC) - dt.timedelta(hours=1)
        token = grants.issue(user_xid="u-1", media_xid="m-1", now=past)
        with pytest.raises(Exception) as exc:
            grants.verify(token, user_xid="u-1", media_xid="m-1")
        assert exc.value.code == "grant_expired"

    def test_a_tampered_payload_is_refused(self):
        """The failure the placeholder had: a plain hash of public inputs can be
        recomputed by anyone. An HMAC over the app secret cannot."""
        token = grants.issue(user_xid="u-1", media_xid="m-1")
        version, packed, signature = token.split(".")
        forged = grants._encode({"u": "u-2", "m": "m-1", "e": 9_999_999_999})
        tampered = f"{version}.{forged.split('.')[1]}.{signature}"
        with pytest.raises(Exception) as exc:
            grants.verify(tampered, user_xid="u-2", media_xid="m-1")
        assert exc.value.code == "grant_bad_signature"

    @pytest.mark.parametrize("token", ["", "garbage", "v1.only-two", "v9.a.b"])
    def test_malformed_grants_are_refused_cleanly(self, token):
        with pytest.raises(Exception) as exc:
            grants.verify(token, user_xid="u-1", media_xid="m-1")
        assert exc.value.code in ("grant_malformed", "grant_version_unsupported",
                                 "grant_bad_signature")

    def test_a_grant_is_not_a_session_token(self):
        """Domain separation: both derive from `jwt_secret`, and a bug in one
        must not become an authentication bypass in the other."""
        import jwt

        from app.platform.config import settings

        token = grants.issue(user_xid="u-1", media_xid="m-1")
        with pytest.raises(jwt.PyJWTError):
            jwt.decode(token, settings().jwt_secret, algorithms=["HS256"])

    def test_a_grant_naming_a_suspended_account_is_not_honoured(
            self, client, db, seed, store):
        """A grant lives for two minutes. A safety ban must take effect inside
        those two minutes, not after them."""
        media_xid = str(db.scalar(text("""
            INSERT INTO media_assets (owner_user_id, kind, bucket, storage_key,
                                      content_type, bytes, checksum_sha256, status)
            VALUES (:u, 'audio', 'test-media', 'k', 'audio/mp4', 4, 'x', 'ready')
            RETURNING xid
        """).bindparams(u=seed["student"].id)))
        db.execute(text("UPDATE users SET status = 'suspended' WHERE id = :u")
                   .bindparams(u=seed["student"].id))
        db.flush()

        grant = grants.issue(user_xid=str(seed["student"].xid), media_xid=media_xid)
        r = client.get(f"/api/v1/media/{media_xid}/content?grant={grant}")
        assert r.status_code == 403
        assert r.json()["code"] == "account_inactive"


class TestExamAudioGrant:
    def test_the_exam_grant_is_a_real_signature_bound_to_the_student(
            self, db, published, clock, store):
        """Replaces a SHA-256 of public inputs, which anyone could recompute."""
        from app.modules.exam.session import ExamSession
        from app.modules.qtypes.registry import default_scorer

        media_xid = db.scalar(text("""
            INSERT INTO media_assets (owner_user_id, kind, bucket, storage_key,
                                      content_type, bytes, checksum_sha256, status)
            VALUES (:u, 'audio', 'test-media', 'k', 'audio/mp4', 4, 'x', 'ready')
            RETURNING xid
        """).bindparams(u=published["author"].id))
        track = db.scalar(text("""
            INSERT INTO audio_tracks (owner_user_id, title, master_media_id, status)
            VALUES (:u, 'S1', (SELECT id FROM media_assets WHERE xid = :m), 'ready')
            RETURNING id
        """).bindparams(u=published["author"].id, m=media_xid))
        # Through the ORM, not raw SQL: the seed built this section via the ORM,
        # so it is in the identity map and a raw UPDATE would be invisible to the
        # `session.get()` the exam session performs.
        published["section"].audio_track_id = track
        published["section"].skill = "listening"
        db.flush()

        exam = ExamSession(db, default_scorer(), clock, grace_seconds=30)
        attempt = exam.start(user_id=published["student"].id,
                             test_version_id=published["test_version"].id)
        issued = exam.audio_grant(attempt, 1)

        assert issued["media_xid"] == str(media_xid)
        claim = grants.verify(issued["grant"], user_xid=str(published["student"].xid),
                              media_xid=str(media_xid), now=clock.now())
        assert claim.attempt_xid == str(attempt.xid)
        assert claim.purpose == "exam"          # play-once section
        # And it does not open the file for anyone else. Named exception and
        # named code, not a bare `Exception`: a signature change that made this
        # raise TypeError would otherwise satisfy the assertion, and the test
        # would go on passing while checking nothing.
        with pytest.raises(Forbidden) as refused:
            grants.verify(issued["grant"], user_xid=str(published["author"].xid),
                          media_xid=str(media_xid), now=clock.now())
        assert refused.value.code == "grant_wrong_user"


@needs_ffmpeg
class TestTheUploadIsTheFileTheTeacherChose:
    """Two declared values that nothing checked.

    `AudioTrackCreate.checksum_sha256` was accepted by the router and dropped —
    there was no column to put it in. And `media_uploads` records
    `expected_bytes` at open and `received_bytes` at complete, **in the same
    row**, and nothing ever compared them.

    Probed before any of this was written: an upload declaring 8,640,078 bytes
    over two parts, with only part 1 sent, completed with 202 and ingested to a
    `ready` track of 54,612 ms. A teacher's connection drops mid-upload and the
    platform serves 55 seconds of a 90-second listening section. The questions
    after the cut refer to audio nobody heard, and the server — the sole
    authority on scoring — marks them wrong. That is not a corrupted file
    somebody notices; it is a paper that looks fine and is not.
    """

    def _open(self, client, auth, source: Path, *, declared_bytes=None,
              checksum=None):
        body = {"title": "Section 1", "accent": "en-GB", "filename": source.name,
                "bytes": declared_bytes or source.stat().st_size,
                "content_type": "audio/wav", "attestation": ATTESTATION}
        if checksum is not None:
            body["checksum_sha256"] = checksum
        return client.post("/api/v1/audio-tracks", headers=auth, json=body)

    def _run(self, client, auth, db, store, source: Path, scratch: Path, *,
             upload: bytes | None = None, declared_bytes=None, checksum=None):
        """Open, PUT (optionally something other than `source`), complete, ingest."""
        from app.modules.content import media as media_service

        opened = self._open(client, auth, source, declared_bytes=declared_bytes,
                            checksum=checksum)
        assert opened.status_code == 201, opened.text
        session = opened.json()["upload"]

        data = source.read_bytes() if upload is None else upload
        size = session["part_size"]
        for part in session["presigned_urls"]:
            chunk = data[part["offset"]:part["offset"] + size]
            if not chunk:
                break
            assert _put_part(client, part, chunk).status_code == 200
        reported = max(1, -(-len(data) // size))
        client.post(f"/api/v1/uploads/{session['xid']}", headers=auth,
                    json={"parts": [{"n": n, "etag": f"etag-{n}"}
                                    for n in range(1, reported + 1)]})

        asset_id = db.scalar(
            text("SELECT id FROM media_assets WHERE xid = CAST(:x AS uuid)")
            .bindparams(x=session["media_xid"]))
        media_service.ingest_audio(db, store, asset_id,
                                   now=dt.datetime.now(dt.UTC), scratch=scratch)
        return asset_id

    def _asset(self, db, asset_id):
        return db.execute(text("""
            SELECT status, checksum_sha256, duration_ms, processing_error
            FROM media_assets WHERE id = :i
        """).bindparams(i=asset_id)).mappings().one()

    # ── the bytes ────────────────────────────────────────────────────

    def test_a_truncated_upload_does_not_become_a_track(self, client, author_auth,
                                                        db, store, tmp_path):
        """The 90-second section that arrives as 55. Two parts declared, one sent."""
        big = _tone(tmp_path / "big.wav", seconds=90)
        first_part_only = big.read_bytes()[:5 * 1024 * 1024]
        asset_id = self._run(client, author_auth, db, store, big, tmp_path,
                             upload=first_part_only,
                             declared_bytes=big.stat().st_size)
        row = self._asset(db, asset_id)
        assert row["status"] == "failed", row["processing_error"]
        assert str(big.stat().st_size) in row["processing_error"]
        assert str(len(first_part_only)) in row["processing_error"]

    def test_the_author_is_told_which_way_it_is_wrong(self, client, author_auth,
                                                      db, store, tmp_path):
        """Content feedback, not an incident. The teacher needs to know it was
        THEIR file that was short, in the place the API shows them."""
        big = _tone(tmp_path / "big.wav", seconds=90)
        asset_id = self._run(client, author_auth, db, store, big, tmp_path,
                             upload=big.read_bytes()[:5 * 1024 * 1024],
                             declared_bytes=big.stat().st_size)
        assert "missing" in self._asset(db, asset_id)["processing_error"]
        assert db.scalar(text("SELECT status FROM audio_tracks")) == "failed"

    def test_more_bytes_than_declared_also_fails(self, client, author_auth, db,
                                                 store, tmp_path):
        """The other direction. Not a truncation, but the declaration and the
        object still disagree, and a check that only looks one way is one a
        client can walk around by under-declaring."""
        wav_file = _tone(tmp_path / "t.wav", seconds=4)
        asset_id = self._run(client, author_auth, db, store, wav_file, tmp_path,
                             declared_bytes=wav_file.stat().st_size - 4096)
        row = self._asset(db, asset_id)
        assert row["status"] == "failed"
        assert "more" in row["processing_error"]

    # ── the checksum ─────────────────────────────────────────────────

    def test_the_same_length_but_not_the_same_file(self, client, author_auth, db,
                                                   store, tmp_path):
        """What the byte count cannot see.

        A part PUT to the wrong presigned URL assembles to exactly the right
        length out of exactly the right pieces, in the wrong order. So does a
        block corrupted in transit. Both decode; the audio is simply not what the
        teacher recorded.
        """
        wav_file = _tone(tmp_path / "t.wav", seconds=6)
        data = wav_file.read_bytes()
        mangled = data[:200_000] + bytes(100_000) + data[300_000:]
        assert len(mangled) == len(data)

        asset_id = self._run(
            client, author_auth, db, store, wav_file, tmp_path, upload=mangled,
            checksum=hashlib.sha256(data).hexdigest())
        row = self._asset(db, asset_id)
        assert row["status"] == "failed", row["processing_error"]
        assert "checksum" in row["processing_error"]

    def test_that_same_mangled_file_transcodes_fine_without_a_checksum(
            self, client, author_auth, db, store, tmp_path):
        """The control, and the reason the previous test means anything.

        The mangled file is valid audio — ffmpeg has no complaint about it, and
        neither does the loudness gate. Declaring the checksum is the ONLY thing
        standing between it and a published listening section.
        """
        wav_file = _tone(tmp_path / "t.wav", seconds=6)
        data = wav_file.read_bytes()
        mangled = data[:200_000] + bytes(100_000) + data[300_000:]
        asset_id = self._run(client, author_auth, db, store, wav_file, tmp_path,
                             upload=mangled)
        assert self._asset(db, asset_id)["status"] == "ready"

    def test_a_matching_checksum_publishes_normally(self, client, author_auth, db,
                                                    store, tmp_path):
        """A gate that refuses good uploads gets switched off within a week."""
        wav_file = _tone(tmp_path / "t.wav", seconds=6)
        asset_id = self._run(
            client, author_auth, db, store, wav_file, tmp_path,
            checksum=hashlib.sha256(wav_file.read_bytes()).hexdigest())
        assert self._asset(db, asset_id)["status"] == "ready"

    @pytest.mark.parametrize("shape", [str.upper, lambda s: f"  {s}\n"])
    def test_case_and_surrounding_whitespace_are_not_a_mismatch(
            self, client, author_auth, db, store, tmp_path, shape):
        """Hex is case-insensitive, and `sha256sum` output has a newline on it.

        Failing a correct upload because the client used `%X`, or piped a digest
        straight out of a shell, is how a field stops being sent — and this one
        is optional, so a client that finds it fussy simply omits it and loses
        the check.
        """
        wav_file = _tone(tmp_path / "t.wav", seconds=6)
        asset_id = self._run(
            client, author_auth, db, store, wav_file, tmp_path,
            checksum=shape(hashlib.sha256(wav_file.read_bytes()).hexdigest()))
        assert self._asset(db, asset_id)["status"] == "ready"

    def test_declaring_nothing_is_allowed(self, client, author_auth, db, store,
                                          tmp_path):
        """Optional in the schema and optional here. A client that does not hash
        its file is not doing anything wrong — it just gets one check instead of
        two."""
        wav_file = _tone(tmp_path / "t.wav", seconds=4)
        asset_id = self._run(client, author_auth, db, store, wav_file, tmp_path)
        assert self._asset(db, asset_id)["status"] == "ready"

    # ── where the values live ────────────────────────────────────────

    @pytest.mark.parametrize("bad", [
        "not-a-hash",
        "abc123",                                        # right alphabet, too short
        "a" * 63,
        "a" * 64 + " (sha256)",                          # a real digest, plus junk
        "a" * 65,
        "z" * 64,                                        # right length, not hex
    ])
    def test_a_malformed_checksum_is_refused_before_the_bytes_are_sent(
            self, client, author_auth, tmp_path, bad):
        """Same rule as every other check at this door. Storing it and failing
        the ingest thirty seconds later spends the teacher's bandwidth to deliver
        the same news — and the message it delivers would be the wrong one:
        "this file does not match", about a file that is perfectly fine.

        The `(sha256)` case is why the pattern is anchored. A digest with a label
        stuck to it contains a valid digest, so an unanchored search accepts it,
        stores the whole string, and then fails every upload that carries one.
        """
        wav_file = _tone(tmp_path / "t.wav", seconds=2)
        refused = self._open(client, author_auth, wav_file, checksum=bad)
        assert refused.status_code == 422, refused.text
        assert any(f["code"] == "CHECKSUM_MALFORMED"
                   for f in refused.json()["findings"])

    def test_the_declaration_is_recorded_on_the_upload(self, client, author_auth,
                                                       db, tmp_path):
        wav_file = _tone(tmp_path / "t.wav", seconds=2)
        digest = hashlib.sha256(wav_file.read_bytes()).hexdigest()
        assert self._open(client, author_auth, wav_file,
                          checksum=digest.upper()).status_code == 201
        assert db.scalar(text("SELECT declared_checksum_sha256 FROM media_uploads")) \
            == digest

    def test_an_asset_with_no_upload_session_still_ingests(self, client,
                                                           author_auth, db, store,
                                                           tmp_path):
        """Not every media asset comes from a resumable upload.

        `speaking.py` writes `media_assets` rows directly for safety-report
        evidence — no `media_uploads` row, so nothing was ever declared about
        them. The join that fetches the declaration returns NULLs there, and a
        check that treated "nothing declared" as "declared zero" would fail every
        one of those assets the day anyone wired transcoding for them.
        """
        from app.modules.content import media as media_service

        wav_file = _tone(tmp_path / "t.wav", seconds=4)
        opened = self._open(client, author_auth, wav_file).json()["upload"]
        _upload_file(client, opened, wav_file)
        client.post(f"/api/v1/uploads/{opened['xid']}", headers=author_auth,
                    json={"parts": _parts_for(wav_file)})
        asset_id = db.scalar(
            text("SELECT id FROM media_assets WHERE xid = CAST(:x AS uuid)")
            .bindparams(x=opened["media_xid"]))

        db.execute(text("DELETE FROM media_uploads WHERE media_asset_id = :i")
                   .bindparams(i=asset_id))
        db.flush()
        media_service.ingest_audio(db, store, asset_id,
                                   now=dt.datetime.now(dt.UTC), scratch=tmp_path)
        assert self._asset(db, asset_id)["status"] == "ready"

    def test_the_computed_checksum_lands_on_the_asset(self, client, author_auth,
                                                      db, store, tmp_path):
        """`media_assets_checksum_idx` exists so a platform admin can ask which
        centres uploaded the same file. That only works if the value is the hash
        of the master, and nothing asserted it was."""
        wav_file = _tone(tmp_path / "t.wav", seconds=4)
        asset_id = self._run(client, author_auth, db, store, wav_file, tmp_path)
        assert self._asset(db, asset_id)["checksum_sha256"] == \
            hashlib.sha256(wav_file.read_bytes()).hexdigest()


# ── helpers ──────────────────────────────────────────────────────────

def _tone(path: Path, *, seconds: int, frequency: int = 220) -> Path:
    """A plain sine, long enough to be multipart when asked for.

    Not the `wav` fixture: these tests need a controlled LENGTH more than they
    need the dynamic range that fixture exists to provide.
    """
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
         "-i", f"sine=frequency={frequency}:duration={seconds}:sample_rate=48000",
         "-ac", "2", "-c:a", "pcm_s16le", str(path)], check=True)
    return path


def _put_part(client, part: dict, data: bytes):
    return client.put(_local(part["url"]), content=data)


def _local(url: str) -> str:
    """Strip the configured public base so TestClient can route it."""
    from urllib.parse import urlparse

    parsed = urlparse(url)
    return f"{parsed.path}?{parsed.query}"


def _upload_file(client, upload: dict, source: Path) -> None:
    data = source.read_bytes()
    size = upload["part_size"]
    for part in upload["presigned_urls"]:
        chunk = data[part["offset"]:part["offset"] + size]
        if not chunk:
            break
        assert _put_part(client, part, chunk).status_code == 200


def _parts_for(source: Path) -> list[dict]:
    size = 5 * 1024 * 1024
    total = max(1, -(-source.stat().st_size // size))
    return [{"n": n, "etag": f"etag-{n}"} for n in range(1, total + 1)]


def _ingest(client, auth, db, store, source: Path, scratch: Path, *,
            expect_ready: bool = True) -> int:
    """The full path: open, upload, complete, then run the ingest actor's work."""
    from app.modules.content import media as media_service

    upload = create_track(client, auth, filename=source.name,
                          bytes_=source.stat().st_size).json()["upload"]
    _upload_file(client, upload, source)
    client.post(f"/api/v1/uploads/{upload['xid']}", headers=auth,
                json={"parts": _parts_for(source)})

    asset_id = db.scalar(text("SELECT id FROM media_assets WHERE xid = CAST(:x AS uuid)")
                         .bindparams(x=upload["media_xid"]))
    media_service.ingest_audio(db, store, asset_id, now=dt.datetime.now(dt.UTC),
                               scratch=scratch)
    if expect_ready:
        assert db.scalar(text("SELECT status FROM media_assets WHERE id = :i")
                         .bindparams(i=asset_id)) == "ready"
    return asset_id


def _delivery_and_student(db, master_id: int, seed) -> tuple[str, str]:
    media_xid = str(db.scalar(text("""
        SELECT xid FROM media_assets WHERE derived_from_id = :i
    """).bindparams(i=master_id)))
    return media_xid, str(seed["student"].xid)
