// The lint config this project's `npm run lint` script has always referred to
// and never had.
//
// `package.json` has carried a `lint` script since the console was created, and
// there was no config file and no eslint in `devDependencies` — so the script
// failed for everyone with "couldn't find an eslint.config file", and every
// agent that tried to run it this session reported the same thing. A script
// that cannot run is worse than no script: it reads as a gate somebody is
// passing.
//
// **What this is for, given `tsc` already runs.** TypeScript here is strict
// with `noUncheckedIndexedAccess` and `exactOptionalPropertyTypes`, which is a
// far stronger net than a linter — so this is deliberately NOT a style config.
// It is the small set of things the compiler cannot see:
//
//   * a floating promise, which in this codebase means an unawaited mutation
//     whose failure never reaches the error banner;
//   * a React hook dependency list that has gone stale, which is how a screen
//     shows data from the previous selection;
//   * an `any` that has crept back in, since the whole point of the generated
//     client is that the contract is typed.
//
// Formatting rules are absent on purpose. Nothing here reformats code, so a
// formatting rule would only ever be noise in a diff.

import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Generated, and regenerated by `make web-codegen`. Linting it would mean
    // fixing findings that come back on the next contract change.
    ignores: ["dist/**", "src/api/schema.d.ts", "node_modules/**"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        // Type-aware linting, which is what makes `no-floating-promises`
        // possible at all — it needs to know a call returns a Promise.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // The three that earn their place, as errors.
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "react-hooks/exhaustive-deps": "error",

      // Off, and each for a reason rather than to make the run green.
      //
      // `tsc` already reports unused locals and parameters, with better
      // messages, so these would be a second voice saying the same thing.
      "@typescript-eslint/no-unused-vars": "off",
      // Template literals of numbers and dates are ordinary here — every screen
      // interpolates a count or a timestamp into a sentence.
      "@typescript-eslint/restrict-template-expressions": "off",
      // `unknown` from a caught error is exactly what `problemText` takes, and
      // it is the safe shape rather than a lazy one.
      "@typescript-eslint/no-unsafe-argument": "off",
      // 163 findings, all one deliberate pattern: `throw failure`, where
      // `failure` is the RFC 9457 problem object openapi-fetch returns rather
      // than an Error. That object is the whole point — `problemText` reads
      // `title`, `detail` and the findings array out of it to put a server's
      // own words in front of a teacher. Wrapping it in an Error to satisfy
      // this rule would throw that away, so the rule is wrong about this
      // codebase rather than the codebase being wrong.
      "@typescript-eslint/only-throw-error": "off",
      // `onRequest` and the test's `mintTicket` are async because the interface
      // they implement is async, not because they await anything. Making them
      // sync would break the contract they satisfy.
      "@typescript-eslint/require-await": "off",
      // Parsing JSON and reading a jsonb payload both produce `any` by
      // definition. The three sites are an import preview, a question payload
      // and a regrade impact — each one is server-shaped data the contract
      // types at the boundary and this rule cannot see through.
      "@typescript-eslint/no-unsafe-assignment": "off",
      // Two sites render an authored `word_limit` value that the question-type
      // registry defines as a scalar. The registry is data rather than a type,
      // so the compiler cannot know, and rendering it is the screen's job.
      "@typescript-eslint/no-base-to-string": "off",
      // The generated client unions `string | undefined` with the schema's own
      // nullable, which reads as redundant to the linter and is exactly what
      // `exactOptionalPropertyTypes` requires at the call site.
      "@typescript-eslint/no-redundant-type-constituents": "off",
    },
  },
);
